### ISSUE TITLE
provider conflict issue

### ISSUE THREAD

**Issue by rohitguptanm** [androidbuffer/Kotlinfilepicker#4]
First of all thanks for this awesome library.
I have one issue arises. it is related to file provider. I am using this library in two different app. but I am unable to install both apps together in one device. Due to the conflict of the provider and get below errors.

Error: INSTALL_FAILED_CONFLICTING_PROVIDER: Package couldn't be installed in /data/app/com.myapp1-2: Can't install because provider name com.androidbuffer.kotlinfilepicker.fileprovider (in package com.myapp1) is already used by com.myapp2.

How can I write different authorities in both apps so that both not conflict each other and getting install in one device?

Thanks for help

**Comment by androidbuffer** [comment]
Hi @rohitguptanm we are glad it helped you in someway. Your issue is being resolved and we have release a new build for this, please update your gradle dependency to 
`implementation 'com.github.androidbuffer:kotlinfilepicker:v0.0.3-alpha'`
and let us know if you face this issue again. Thanks for reporting issue .
